Repository tiki/website-home, pull requests merged in 2024-01, with the labels that each got.

#199 fix: force light theme in dark mode
  subscription-ui/index.html
Labels: fix

#203 docs: update readme
  subscription-ui/README.md
Labels: docs

#206 fix linter and format
  subscription-ui/.eslintrc.cjs
  subscription-ui/src/App.vue
  subscription-ui/src/assets/style.css
  subscription-ui/src/components/SubscriptionUi.vue
  subscription-ui/src/components/cleanroomSelect.vue
  subscription-ui/src/components/queryCost.vue
  subscription-ui/src/components/queryEditor.vue
  subscription-ui/src/components/queryInfo.vue
  subscription-ui/src/components/querySample.vue
  subscription-ui/src/components/tableTaxonomy.vue
  subscription-ui/src/interfaces/Cleanroom.ts
  subscription-ui/src/interfaces/ProfileInfo.ts
  subscription-ui/src/interfaces/QueryInfo.ts
  subscription-ui/src/interfaces/Subscription.ts
  subscription-ui/src/interfaces/TableTaxonomies.ts
  subscription-ui/src/main.ts
  subscription-ui/src/subscription/index.ts
Labels: chore

#207 chore: Reduce JS and CSS bundle sizes
  subscription-ui/package-lock.json
  subscription-ui/package.json
  subscription-ui/postcss.config.js
  subscription-ui/vite.config.ts
Labels: chore

#210 Initial GitHub Actions workflow for deploying to Cloudflare Pages
  .github/workflows/publish.yml
Labels: chore

#213 Fix/update estimate builder
  subscription-ui/src/App.vue
  subscription-ui/src/assets/images/alert-icon.svg
  subscription-ui/src/assets/images/cancel-icon.svg
  subscription-ui/src/assets/images/closed-arrow.svg
  subscription-ui/src/assets/images/green-select-arrow.svg
  subscription-ui/src/assets/images/loading-icon.svg
  subscription-ui/src/assets/images/red-crossmark.svg
  subscription-ui/src/assets/images/select-arrow.svg
  subscription-ui/src/assets/images/tiki-pineapple-block.svg
  subscription-ui/src/components/AlertComponent.vue
  subscription-ui/src/components/AuthSheet.vue
  subscription-ui/src/components/HeaderTitle.vue
  subscription-ui/src/components/InputComponent.vue
  subscription-ui/src/components/SubscriptionUi.vue
  subscription-ui/src/components/TextButton.vue
  subscription-ui/src/components/cleanroomSelect.vue
  subscription-ui/src/components/queryEditor.vue
  subscription-ui/src/components/queryInfo.vue
  subscription-ui/src/components/tableTaxonomy.vue
  subscription-ui/src/interfaces/BuilderState.ts
  subscription-ui/src/interfaces/ButtonState.ts
  subscription-ui/src/subscription/index.ts
  subscription-ui/tailwind.config.js
Labels: fix

#215 Fix/estimate times out
  subscription-ui/src/components/InputComponent.vue
  subscription-ui/src/components/PurchaseSheet.vue
  subscription-ui/src/components/SubscriptionUi.vue
  subscription-ui/src/subscription/index.ts
Labels: fix

#220 Fix: query font family
  subscription-ui/src/assets/style.css
  subscription-ui/src/components/queryEditor.vue
Labels: fix

#224 fix: image low quality
  subscription-ui/src/assets/images/tiki-pineapple-block.png
Labels: fix

#222 Fix: table results overflow
  subscription-ui/src/assets/style.css
  subscription-ui/src/components/InputComponent.vue
  subscription-ui/src/components/cleanroomSelect.vue
  subscription-ui/src/components/querySample.vue
Labels: fix

#233 Fix/website UI tweaks
  subscription-ui/src/components/AuthSheet.vue
  subscription-ui/src/components/InputComponent.vue
  subscription-ui/src/components/PurchaseSheet.vue
  subscription-ui/src/components/SubscriptionUi.vue
  subscription-ui/src/components/queryEditor.vue
  subscription-ui/src/components/queryInfo.vue
  subscription-ui/src/components/tableTaxonomy.vue
Labels: fix

#232 fix: copies
  subscription-ui/src/components/HeaderTitle.vue
  subscription-ui/src/components/PurchaseSheet.vue
  subscription-ui/src/components/SubscriptionUi.vue
Labels: fix
